spring:
  data:
    redis:
      host: 135.72.67.97
      port: 30079
      password: rediscloud
      database: 2
  cache:
    type: redis
    redis:
      time-to-live: 600000
  application:
    name: corecraft
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.168.87.32:3306/corecraft?serverTimezone=GMT%2B8&useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&allowMutiQueries=true&useServerPrepStmts=true&useSSL=false
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: PET_Hikari
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      login-timeout: 500
      validation-timeout: 1000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 1000

server:
  port: 8089
  servlet:
    context-path:  /api

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


logging:
  level:
    root: info

app:
  storage:
    avatar-dir: ${user.dir}/storage/avatars
